# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Compile LateX
      uses: vinay0410/tectonic-action@v1.1.2
      with:
        # Path of Tex File
        tex_path: ProjectStolovka/ProjectStolovka_report/matmex_mywork.tex
        # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
        push: no
