name: Compile-LaTeX-with-tectonic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile-my-docs:
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Compile spbu report
      uses: vinay0410/tectonic-action@v1.1.2
      with:
        # Path of Tex File
        tex_path: ProjectStolovka/ProjectStolovka_report/matmex_mywork.tex
        # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
        push: yes
